# Generated by Django 4.2.6 on 2023-10-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttgapp', '0005_delete_degreeprogram_delete_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Dept_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('Facultyid', models.IntegerField()),
                ('room_no', models.CharField(max_length=40)),
            ],
        ),
    ]
