# Generated by Django 4.2.6 on 2023-10-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttgapp', '0006_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degreeprogram',
            fields=[
                ('Dept_name', models.CharField(max_length=40)),
                ('Deg_name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_id', models.IntegerField()),
                ('sem_num', models.IntegerField()),
                ('Deg_name', models.CharField(max_length=40)),
                ('Reg_year', models.IntegerField()),
            ],
        ),
    ]
