# Generated by Django 4.2.6 on 2023-10-28 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttgapp', '0007_degreeprogram_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeprogram',
            name='Dept_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgapp.department'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='Deg_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgapp.degreeprogram'),
        ),
    ]
