# Generated by Django 4.2.6 on 2023-10-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttgapp', '0008_alter_degreeprogram_dept_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='Reg_year',
            field=models.CharField(max_length=50),
        ),
    ]
