# Generated by Django 4.2.6 on 2023-10-29 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttgapp', '0009_alter_semester_reg_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
