# Generated by Django 4.2.6 on 2023-10-29 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttgapp', '0010_delete_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_id', models.IntegerField()),
                ('sem_num', models.IntegerField()),
                ('Reg_year', models.CharField(max_length=50)),
                ('Deg_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgapp.degreeprogram')),
            ],
        ),
    ]
