# Generated by Django 4.2.6 on 2023-10-29 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttgapp', '0011_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('Sub_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sub_title', models.CharField(max_length=40)),
                ('Credit', models.IntegerField()),
                ('Reg_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ttgapp.semester')),
                ('sem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ttgapp.semester')),
            ],
        ),
    ]
