# Generated by Django 4.2.6 on 2023-10-29 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttgapp', '0014_alter_subject_sem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fac_id', models.IntegerField()),
                ('Fac_name', models.CharField(max_length=40)),
                ('Dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgapp.department')),
                ('sub_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgapp.subject')),
            ],
        ),
    ]
