# Generated by Django 4.2.6 on 2023-10-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttgapp', '0015_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='sem_id',
            field=models.CharField(max_length=10),
        ),
    ]
