# Generated by Django 4.2.6 on 2023-10-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttgapp', '0016_alter_semester_sem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='condition',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
