# Generated by Django 4.2.6 on 2023-10-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttgapp', '0017_semester_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='condition',
        ),
    ]
