# Generated by Django 4.2.6 on 2023-10-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttgapp', '0018_remove_semester_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('sub_code', models.IntegerField()),
                ('sub_title', models.CharField(max_length=50)),
                ('fac_name', models.CharField(max_length=50)),
            ],
        ),
    ]
