# Generated by Django 4.2.6 on 2023-11-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttgapp', '0019_timetabledata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetabledata',
            name='sub_code',
            field=models.CharField(),
        ),
    ]
