# Generated by Django 4.2.6 on 2023-11-04 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttgapp', '0021_alter_timetabledata_sub_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetabledata',
            name='fac_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttgapp.faculty'),
        ),
    ]
