# Generated by Django 4.2.6 on 2023-11-04 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ttgapp', '0022_alter_timetabledata_fac_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetabledata',
            name='sub_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='ttgapp.subject'),
        ),
        migrations.AlterField(
            model_name='timetabledata',
            name='sub_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title', to='ttgapp.subject'),
        ),
    ]
